### ISSUE TITLE
Conway hard-fork (HFC)

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-node-tests#2007]
- [x] check successful era migration - after era migration:
> - blocks are still created by stake pools
> - rewards are still paid
> - all the existing scripts are passing (in the new era) (Shelley/Mary/Alonzo/Vasil transactions) - blocks, rewards, pool operation, etc

- [x] confirm that old nodes halt at the HF
- [x] `query tip` CLI command returns correct values
- [x] `query protocol parameters` CLI command returns correct values (protocol version included)
- [x] `transaction view` output works for Conway transactions and it contains all the new parameters when using PlutusV2 and PlutusV3

> - reference inputs, collateral return, collateral total, more data in the transaction outs (inline datums, reference scripts, other scenarios)
- [x] all the previous (Babbage) functionalities continue to work in the Conway era (after the hard fork)
- [x] after the HF, the correct protocol version is advised in the block headers
- [x]  upgrade nightly pipelines with the Conway era scripts
- [x] check consistency of the previews era related to the functionalities from the next era (make sure we avoid issues like these - [here](https://github.com/input-output-hk/cardano-node/issues/4424)) 

- [x] cost model V3 (it is not clear if we will have a new cost model yet) 
   - [x] the next epoch after the HF, the cost model will need to be updated for Plutus V3 to take effect 
   - [x] the cost of the transactions without Plutus scripts should not be impacted by the new cost model --> https://github.com/input-output-hk/cardano-node-tests/issues/996#issuecomment-1144546694
   - [x] we can change any of the cost models with an update proposal (make and confirm changes to different parameters of both cost-model_V, cost-model_V2, and cost-model_V3 for parameters having the same name and also different names)

- [x] there is full backward compatibility between PlutusV1, PlutusV2, and PlutusV3

- [ ] leaderlogs - compare the results in the epoch before and after the hard fork (avoid issues like these - [here](https://github.com/input-output-hk/cardano-node/issues/4478))

- [ ] HFC Mainnet approach works as expected --> similar scenario with [this one but for Conway](https://github.com/input-output-hk/cardano-node-tests/issues/1158)

**Comment by dorin100** [comment]
@mkoura, @james-iohk, @CarlosLopezDeLara, @disassembler can you please review this ticket detailing our plan to test the HFC on a local cluster and let us know if we missed anything?

**Comment by dorin100** [comment]
From @james-iohk: 
- assertions on node logging (confirming the HF and protocol parameter upgrades are successful)
